#!/bin/sh

set -e

cp /etc/skel/.config/examples/.profile /etc/skel/
cp /usr/share/backgrounds/pika/can_i_come_in__by_neytirix_ddoss9c.jpg /usr/share/sddm/themes/Orchis/
cp /etc/skel/.config/examples/theme.conf.user /usr/share/sddm/themes/Orchis/
